-- Run this in Supabase SQL Editor.

create table if not exists public.saris (
  id bigint generated by default as identity primary key,
  name text not null default '',
  fabric text not null,
  region text not null,
  tags text[] not null default '{}',
  price_min integer not null check (price_min >= 0),
  price_max integer not null check (price_max >= price_min),
  quantity integer not null default 0 check (quantity >= 0),
  reserved boolean not null default false,
  image_data text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  sari_id bigint references public.saris (id) on delete set null,
  sari_name text not null,
  buyer text not null,
  qty integer not null check (qty > 0),
  actual_price numeric(10,2) not null check (actual_price > 0),
  method text not null check (method in ('Cash', 'Venmo', 'Zelle', 'UPI')),
  sale_date date not null,
  created_at timestamptz not null default now()
);

alter table public.saris
  add column if not exists tags text[] not null default '{}';

alter table public.saris
  alter column name set default '';

create index if not exists idx_transactions_sari_id on public.transactions (sari_id);
create index if not exists idx_transactions_sale_date on public.transactions (sale_date desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_saris_updated_at on public.saris;
create trigger trg_saris_updated_at
before update on public.saris
for each row
execute function public.set_updated_at();

create or replace function public.apply_transaction_inventory_delta()
returns trigger
language plpgsql
as $$
declare
  new_qty integer;
begin
  if tg_op = 'INSERT' then
    if new.sari_id is not null then
      update public.saris
      set quantity = quantity - new.qty,
          reserved = case when quantity - new.qty <= 0 then false else reserved end
      where id = new.sari_id
      returning quantity into new_qty;

      if new_qty is null or new_qty < 0 then
        raise exception 'Not enough inventory for sari_id %', new.sari_id;
      end if;
    end if;
    return new;
  end if;

  if tg_op = 'DELETE' then
    if old.sari_id is not null then
      update public.saris
      set quantity = quantity + old.qty
      where id = old.sari_id;
    end if;
    return old;
  end if;

  if tg_op = 'UPDATE' then
    if old.sari_id = new.sari_id then
      if new.sari_id is not null then
        update public.saris
        set quantity = quantity + old.qty - new.qty,
            reserved = case when quantity + old.qty - new.qty <= 0 then false else reserved end
        where id = new.sari_id
        returning quantity into new_qty;

        if new_qty is null or new_qty < 0 then
          raise exception 'Not enough inventory for sari_id %', new.sari_id;
        end if;
      end if;
    else
      if old.sari_id is not null then
        update public.saris
        set quantity = quantity + old.qty
        where id = old.sari_id;
      end if;

      if new.sari_id is not null then
        update public.saris
        set quantity = quantity - new.qty,
            reserved = case when quantity - new.qty <= 0 then false else reserved end
        where id = new.sari_id
        returning quantity into new_qty;

        if new_qty is null or new_qty < 0 then
          raise exception 'Not enough inventory for sari_id %', new.sari_id;
        end if;
      end if;
    end if;
    return new;
  end if;

  return null;
end;
$$;

drop trigger if exists trg_transactions_inventory_delta on public.transactions;
create trigger trg_transactions_inventory_delta
before insert or update or delete on public.transactions
for each row
execute function public.apply_transaction_inventory_delta();

alter table public.saris enable row level security;
alter table public.transactions enable row level security;

drop policy if exists "Allow full access on saris" on public.saris;
create policy "Allow full access on saris"
on public.saris
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "Allow full access on transactions" on public.transactions;
create policy "Allow full access on transactions"
on public.transactions
for all
to anon, authenticated
using (true)
with check (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'saris'
  ) then
    alter publication supabase_realtime add table public.saris;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'transactions'
  ) then
    alter publication supabase_realtime add table public.transactions;
  end if;
end $$;

insert into public.saris (name, fabric, region, tags, price_min, price_max, quantity, reserved, image_data)
select * from (
  values
    ('Banarasi', 'Silk', 'Banarasi', array['Silk', 'Banarasi'], 130, 180, 3, false, ''),
    ('Kanjeevaram', 'Silk', 'Kanjeevaram', array['Silk', 'Kanjeevaram'], 200, 250, 2, false, ''),
    ('Chanderi', 'Cotton', 'Chanderi', array['Cotton', 'Chanderi'], 45, 95, 5, false, ''),
    ('Patola', 'Silk', 'Patola', array['Silk', 'Patola'], 270, 320, 1, false, ''),
    ('Georgette', 'Georgette', 'Chanderi', array['Georgette', 'Chanderi'], 70, 120, 4, false, ''),
    ('Chiffon', 'Chiffon', 'Banarasi', array['Chiffon', 'Banarasi'], 95, 145, 0, false, '')
) as v(name, fabric, region, tags, price_min, price_max, quantity, reserved, image_data)
where not exists (select 1 from public.saris);
